[platformio]
default_envs = waveshare_esp32_s3_touch_amoled_175b

[env:waveshare_esp32_s3_touch_amoled_175b]
platform = espressif32
board = esp32s3_120_16_8-qio_opi
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
lib_archive = false
extra_scripts = pre:scripts/framework_workarounds.py
lib_deps =
  lvgl/lvgl
  moononournation/GFX Library for Arduino
  bblanchon/ArduinoJson@^6.21.4
  lewisxhe/SensorLib@^0.4.1
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DBOARD_HAS_PSRAM
  -DLV_CONF_PATH=\"lv_conf.h\"