#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define WEATHER_LATITUDE 40.7128f
#define WEATHER_LONGITUDE -74.0060f

#define WEATHER_TIMEZONE_NAME "America/New_York"
#define WEATHER_TZ_POSIX "EST5EDT,M3.2.0/2,M11.1.0/2"

#define WEATHER_USE_METRIC 0